### ISSUE TITLE
Update GCC workflow to new feature "Dependent Contents strategy chooser"

### ISSUE THREAD

**Issue by crandow** [CoreMedia/coremedia-globallink-connect-integration#17]
With CMCC 2007.1, we are able to display a new checkbox that lets a user decide, how the dependent content of a translation workflow should be calculated. 

The checkbox will be displayed automatically, however the variable where this checkbox writes to, needs to be added to the process definition.

=> We need to adapt the process definition of the GCC workflow according to the changes in the file "translation.xml" from OneRepo.

**Comment by mmichaelis** [comment]
Fixed with release for 2007.1.
