### ISSUE TITLE
GlobalLink Settings name hard coded in client extension

### ISSUE THREAD

**Issue by crandow** [CoreMedia/coremedia-globallink-connect-integration#18]
Given I want to define multiple GlobalLink Settings, that are linked to different sites within my settings folder, I have to provide different names for the GlobaLink Settings. 

However in the client extension the name is hard coded, which currently allows only one setting: 
https://github.com/CoreMedia/coremedia-globallink-connect-integration/blob/889503fa092be645abe722480df869aa917b8126/apps/studio-client/src/main/joo/com/coremedia/labs/translation/gcc/studio/GccStudioPluginBase.as#L145

**Expected behavior**
It should be possible to define multiple GlobalLinkSettings.

**Comment by aprantl** [comment]
This currently only affects the setting `dayOffsetForDueDate` which consequently can only be set globally. The connection setting on the other hand can be site specific. The tricky part will be to identify the site which can only be derived from the content set dynamically. 
I am not sure if this should even be implemented. The content set could initially be empty. If you now add content, does the due date automatically adjusts the offset? I'd say no. But we should at least mention this in the documentation.
