### ISSUE TITLE
Direct cancellation of workflow might result into failure

### ISSUE THREAD

**Issue by crandow** [CoreMedia/coremedia-globallink-connect-integration#2]
When cancelling a directly started translation workflow, the GlobalLink-Api will return an error "Submission cannot be cancelled in Pre-process or Delivered state" or an error with an empty response. 

The translation workflow still functions correctly as there is an automatic retry built in. 
After 1 - 2 minutes, the workflow can be cancelled without errors correctly.

**Comment by aprantl** [comment]
I am not sure if we can do something about this or if this only affects our development sandbox at translations.com. It seems to be an edge case and since the translation workflow still functions correctly, I am considering this a minor issue.

**Comment by crandow** [comment]
I also agree that this is a minor issue, however this can cause problems within the contract test for the GlobalLink-Client "DefaultGCExchangeFacadeContractTest.java"
