### ISSUE TITLE
Add documentation for how to adjust the integration to generate a separate workflow for each target locale

### ISSUE THREAD

**Issue by henningSaulCM** [CoreMedia/coremedia-globallink-connect-integration#21]
The current default setup/configuration for the GlobalLink integration will create a single workflow for all selected target locales. 

Having individual workflows for each separate target locale might be more desirable depending on translation/editorial requirements, e.g. to be able to individually "handle" the translations as they are returned for each locale.

Please add documentation for how to adjust the integration to have the system create a separate workflow for each target locale.

**Comment by aprantl** [comment]
Fixed with release:
https://github.com/CoreMedia/coremedia-globallink-connect-integration/releases/tag/2010.1-1
