### ISSUE TITLE
Allow configuring username, password and key via Spring properties

### ISSUE THREAD

**Issue by mtommila** [CoreMedia/coremedia-globallink-connect-integration#25]
The current mechanism for configuring the globallink API username, password and key is to put them to a Settings object and then reference this in the Linked Settings of the homepage. From a security viewpoint this is unacceptable if there is a way to retrieve that Settings object (from the public internet), which would expose the secrets. For example some API of the headless server or a similar API might expose the secret content. Nb. the homepage is published and so the linked Settings object has to be published as well.

The proposed solution is to allow configuring these secrets using Spring properties, as a fallback to the current mechanism.

Trying to otherwise hide the secret Settings object is impractical. At least Studio users would be able to see it and we don't need any Studio users to see globallink API secrets.

**Comment by aprantl** [comment]
I agree in terms of the risks. By default neither the CAE nor the Headless server have access to these files, if you restrict the read rights to administrator users. Implementing the fallback mechanism sounds reasonable though. I am just not sure how you would allow setting different credentials per site which is easily doable with the content settings. But maybe it is good enough for a start, if you only have one GlobalLink account.

**Comment by mtommila** [comment]
I think by default at least CAE (the "webserver" system account) has read access to everything. It belongs to the "system" group, which has read-only access to all content and all folders starting from the root folder.
