### ISSUE TITLE
Git subtree approach

### ISSUE THREAD

**Issue by mtommila** [CoreMedia/coremedia-globallink-connect-integration#28]
The documentation for the connector recommends either using `git submodule` or just copying the connector files to the CoreMedia Blueprint workspace. However I think that there is a third possible approach, which perhaps combines some of the good sides of the two other approaches: `git subtree`.

The approach is roughly as follows:
* Clone the coremedia-globallink-connect-integration repository
* In your CoreMedia Blueprint workspace repository checkout a new branch (let's say `gcc` for example)
* In your CoreMedia Blueprint workspace repository, add the connector as a git subtree, e.g.
`git subtree add --prefix=modules/extensions ../coremedia-globallink-connect-integration master --squash`
* Merge the `gcc` branch to your main branch in your workspace repo
* In the future when there are changes to the connector, checkout the `gcc` branch and cherry-pick the new commit(s), e.g.
`git fetch ../coremedia-globallink-connect-integration`
`git cherry-pick -m 1 -Xsubtree=modules/extensions 77695e2b39f3eb36fdaca3ee992e8702c49f23fa`
and merge the `gcc` branch to your main branch again.

Benefits:
* No hassle with two Git repositories that `git submodule` gives
* You can modify the connector files (you don't need to fork the connector repo to do that)
* In the future, you can cherry-pick commits from the connector repo and merge them to your code easily

Please feel free to consider this and update the documentation if you think it would be useful.

**Comment by aprantl** [comment]
Fixed with release for v11.2110.1
