### ISSUE TITLE
Links to mock facade documentation in README broken

### ISSUE THREAD

**Issue by aprantl** [CoreMedia/coremedia-globallink-connect-integration#5]
Steps to reproduce:
Click on one of the links of the landing page that should lead to the documentation of the mock facade, and you will get a 404.

Other links are probably affected too. I guess this is a regression from the extension refactoring of the 1907 release.

**Comment by mmichaelis** [comment]
23cb934916fef64b5c9a39983f44652cc00a2f05 fixes links in root README.md. On the long run, we should provide more README's and especially a README in `gcc-workflow-server-facade` which then delegates to the other README's.
