### ISSUE TITLE
Error handling in GlobalLink translation workflow breaks

### ISSUE THREAD

**Issue by mtommila** [CoreMedia/coremedia-globallink-connect-integration#61]
**Describe the bug**
There is a bug in the error handling of the GlobalLink translation workflow. If an issue needs to be serialized to JSON, this fails.

The fix should be to change in `GlobalLinkAction`
```
  private static final Gson contentObjectReturnsIdGson = new GsonBuilder()
          .enableComplexMapKeySerialization()
          .registerTypeAdapter(Content.class, new ContentObjectSerializer())
          .create();
```
to
```
  private static final Gson contentObjectReturnsIdGson = new GsonBuilder()
          .enableComplexMapKeySerialization()
          .registerTypeHierarchyAdapter(Content.class, new ContentObjectSerializer())
          .create();
```
i.e. instead of type adapter it should use type hierarchy adapter (I suppose because `Content` is an interface, not a class, so no concrete object can have the exact class `Content`).

I have attached an excerpt of the workflow server log where the error happens. It is from our production system.

**To Reproduce**
1. In Studio, create a content item and send it to translation using the Global Link translation workflow
2. While the content item is being translated, log in using another user to Studio and check out the localized content item that is in translation
3. Wait until the content item comes back from translation
4. As the translation is ready and is downloaded, the workflow server can't update the localized item because it's now checked out by another user

**Expected behavior**
The workflow gracefully goes to the "download error" state and shows in Studio (when clicked) the error that the content item could not be updated because it was checked out by another user. The workflow can continue if the task is accepted and the next step of "retry" is chosen (after checking in or reverting the problematic localized content item).

**Actual behavior**
The workflow escalates because serializing the issue to JSON fails with the stack trace in the attached log.txt file. The only way to continue is to abort and destroy the escalated workflow.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 124.0b8

**Additional context**
Log file excerpt:
[log.txt](https://github.com/CoreMedia/coremedia-globallink-connect-integration/files/14588245/log.txt)

**Comment by mmichaelis** [comment]
Fix applied by #63.
