### ISSUE TITLE
Fix code scanning alert - Arbitrary file access during archive extraction ("Zip Slip")

### ISSUE THREAD

**Issue by mmichaelis** [CoreMedia/coremedia-globallink-connect-integration#64]
Tracking issue for:
- [ ] https://github.com/CoreMedia/coremedia-globallink-connect-integration/security/code-scanning/4

## Rating

While zipping is used from production code, the unzip-feature is (up to now) only used from test code. Thus, overall rating is low, while the issue should still be fixed.

**Comment by rreich** [comment]
False positive: The entry is already validated with PathUtil.isReferringToParent(entry.getName()):
https://github.com/CoreMedia/coremedia-globallink-connect-integration/blob/4c4475f8d6ceb4e215d6cc65f5d6f7fdf445f9bd/apps/workflow-server/gcc-workflow-server-util/src/main/java/com/coremedia/labs/translation/gcc/util/Zipper.java#L85
